services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  shadypayserver:
    image: shadypay
    build:
      context: .
    container_name: shadypayserver_app
    env_file:
      - .env
    depends_on:
      - db
    command: ["/ShadyPayServer/docker/main.sh"]
    ports:
      - "3334:3334"
      - "8000:8000"
      - "4444:4444"


