"""add pin in card

Revision ID: 4b4308e3ef8e
Revises: 362083c4d026
Create Date: 2025-04-06 21:16:38.675033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4308e3ef8e'
down_revision: Union[str, None] = '362083c4d026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('pin', sa.Integer(), nullable=True))
    op.alter_column('user', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['telephone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('card', 'pin')
    # ### end Alembic commands ###
