"""v0.6 update scale in ballance

Revision ID: 8cd7ef46dbb1
Revises: 28b77ae78286
Create Date: 2025-04-08 12:26:28.842856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd7ef46dbb1'
down_revision: Union[str, None] = '28b77ae78286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'balance',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
