"""chenge ballance datatype

Revision ID: e90d39ea4c62
Revises: 459937f98bca
Create Date: 2025-04-07 13:20:21.274724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90d39ea4c62'
down_revision: Union[str, None] = '459937f98bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('procent', sa.Double(), nullable=True))
    op.alter_column('card', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'balance',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('card', 'procent')
    # ### end Alembic commands ###
